sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t isji/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true isji/docker-react npm run test -- --coverage